set(_CATKIN_CURRENT_PACKAGE "z_state_estimator")
set(z_state_estimator_VERSION "0.0.0")
set(z_state_estimator_MAINTAINER "ohrad <ohrad@todo.todo>")
set(z_state_estimator_PACKAGE_FORMAT "2")
set(z_state_estimator_BUILD_DEPENDS "roscpp" "rospy" "sensor_msgs" "geometry_msgs" "rosflight_msgs" "std_msgs" "message_generation")
set(z_state_estimator_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "sensor_msgs" "geometry_msgs" "rosflight_msgs" "std_msgs" "message_generation")
set(z_state_estimator_BUILDTOOL_DEPENDS "catkin")
set(z_state_estimator_BUILDTOOL_EXPORT_DEPENDS )
set(z_state_estimator_EXEC_DEPENDS "roscpp" "rospy" "sensor_msgs" "geometry_msgs" "rosflight_msgs" "std_msgs" "message_runtime")
set(z_state_estimator_RUN_DEPENDS "roscpp" "rospy" "sensor_msgs" "geometry_msgs" "rosflight_msgs" "std_msgs" "message_runtime" "message_generation")
set(z_state_estimator_TEST_DEPENDS )
set(z_state_estimator_DOC_DEPENDS )
set(z_state_estimator_URL_WEBSITE "")
set(z_state_estimator_URL_BUGTRACKER "")
set(z_state_estimator_URL_REPOSITORY "")
set(z_state_estimator_DEPRECATED "")